language: cpp

sudo: required

dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - BUILD_NAME=UBUNTU_TRUSTY_2_7
        - BOOST_PYTHON_NUMPY_EIGEN_PYTHON_VERSION="2.7"
    - os: linux
      compiler: gcc
      env:
        - BUILD_NAME=UBUNTU_TRUSTY_3_4
        - BOOST_PYTHON_NUMPY_EIGEN_PYTHON_VERSION="3.4"
    - os: linux
      compiler: gcc
      env:
        - BUILD_NAME=UBUNTU_XENIAL_2_7
        - BOOST_PYTHON_NUMPY_EIGEN_PYTHON_VERSION="2.7"
        - DOCKER_FILE="ubuntu-xenial"
      services: docker
    - os: linux
      compiler: gcc
      env:
        - BUILD_NAME=UBUNTU_XENIAL_3_5
        - BOOST_PYTHON_NUMPY_EIGEN_PYTHON_VERSION="3.5"
        - DOCKER_FILE="ubuntu-xenial"
      services: docker
    - os: linux
      compiler: gcc
      env:
        - BUILD_NAME=UBUNTU_BIONIC_2_7
        - BOOST_PYTHON_NUMPY_EIGEN_PYTHON_VERSION="2.7"
        - DOCKER_FILE="ubuntu-bionic"
      services: docker
    - os: linux
      compiler: gcc
      env:
        - BUILD_NAME=UBUNTU_BIONIC_3_6
        - BOOST_PYTHON_NUMPY_EIGEN_PYTHON_VERSION="3.6"
        - DOCKER_FILE="ubuntu-bionic"
      services: docker
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env:
        - BUILD_NAME=OSX
        - BOOST_PYTHON_NUMPY_EIGEN_PYTHON_VERSION="3.7"

before_install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker build -t "$DOCKER_FILE" -f ".ci/docker/$DOCKER_FILE" .;
      docker run -itd -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR --env-file .ci/docker/env.list --name my-docker "$DOCKER_FILE";
    fi

install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/install.sh";
    else
      '.ci/install.sh';
    fi

script:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/script.sh";
    else
      '.ci/script.sh';
    fi
